import {
    defineNode,
    NumberInterface,
    SelectInterface,
    NodeInterface,
    IntegerInterface,
    TextareaInputInterface,
    TextInputInterface,

  } from "baklavajs";
  
  export const Desafio = defineNode({
    type: "Desafio",
    title: "Desafio",
    inputs: {
        Numero: () => new SelectInterface("Numero Desafio",1,[
          {"text":"Desafio extra","value":0},
          {"text":"1","value":1},
          {"text":"2","value":2},
          {"text":"3","value":3},
          {"text":"4","value":4},
          {"text":"5","value":5},
          {"text":"6","value":6},
          {"text":"7","value":7},
          {"text":"8","value":8},
          {"text":"9","value":9},
          {"text":"10","value":10},
          {"text":"11","value":11},
          {"text":"12","value":12},
          {"text":"13","value":13},
          {"text":"14","value":14},
          {"text":"15","value":15},
          {"text":"16","value":16},
          {"text":"17","value":17},
          {"text":"18","value":18},
          {"text":"19","value":19},
          {"text":"20","value":20},
          {"text":"21","value":21},
          {"text":"22","value":22},
          {"text":"23","value":23},
          {"text":"24","value":24},
          {"text":"25","value":25},
        ]),
        Recompensa : () => new IntegerInterface("Recompensa (pontos):", 1, 1, 99999),
        TextoLabel: () => new NodeInterface("Texto do desafio:", ""),
        Texto: () => new TextareaInputInterface("Texto"),
        ImagemLabel: () => new NodeInterface("Imagem do desafio:", ""),
        Imagem: () => new TextInputInterface("Imagem URL"),
        DescricaoLabel: () => new NodeInterface("Descrição do desafio:", ""),
        Descricao: () => new TextareaInputInterface("Descrição"),
        RespostaLabel: () => new NodeInterface("Resposta do desafio:", ""),
        Resposta: () => new TextInputInterface("Resposta"),
        DiaDisponibilidadeLabel: () => new NodeInterface("Dia de disponibilidade:", ""),
        DiaDisponibilidade: () => new IntegerInterface("Dia de disponibilidade", 1, 1, 31),
        MesDisponibilidadeLabel: () => new NodeInterface("Mes de disponibilidade:", ""),
          MesDiponibilidade : () => new SelectInterface("Mês", 1, [
            { text: "Janeiro", value: 1 },
            { text: "Fevereiro", value: 2 },
            { text: "Março", value: 3 },
            { text: "Abril", value: 4 },
            { text: "Maio", value: 5 },
            { text: "Junho", value: 6 },
            { text: "Julho", value: 7 },
            { text: "Agosto", value: 8 },
            { text: "Setembro", value: 9 },
            { text: "Outubro", value: 10 },
            { text: "Novembro", value: 11 },
            { text: "Dezembro", value: 12 }
        ]),
        HoraDisponibilidadeLabel: () => new NodeInterface("Hora de disponibilidade:", ""),
        HoraDisponibilidade: () => new TextInputInterface("Hora de disponibilidade",""),
        HorarioExpiracaoLabel: () => new NodeInterface("Hora de expiração:", ""),
        HorarioExpiracao: () => new TextInputInterface("Hora de expiração",""),
        DesbloqueiaCapituloLabel: () => new NodeInterface("Desbloqueia capítulo:", ""),
        DesbloqueiaCapitulo: () => new SelectInterface("Desbloqueia capítulo", 0, [{text: "Não", value: 0}, {text: "1", value: 1}, {text: "2", value: 2}, {text: "3", value: 3}, {text: "4", value: 4}, {text: "5", value: 5}, {text: "6", value: 6}, {text: "7", value: 7}, {text: "8", value: 8}, {text: "9", value: 9}, {text: "10", value: 10}]),
        CapituloRecomendadoLabel: () => new NodeInterface("Capítulo recomendado:", ""),
        CapituloRecomendado: () => new SelectInterface("Desbloqueia capítulo", 0, [{text: "Nenhum", value: 0}, {text: "1", value: 1}, {text: "2", value: 2}, {text: "3", value: 3}, {text: "4", value: 4}, {text: "5", value: 5}, {text: "6", value: 6}, {text: "7", value: 7}, {text: "8", value: 8}, {text: "9", value: 9}, {text: "10", value: 10}]),
      }
  });
  